### ISSUE TITLE
example `sine_synth.rs` crashes sometimes

### ISSUE THREAD

**Issue by crsaracco** [rust-dsp/rust-vst#20]
I'm not sure how strict we want to be with the examples, on a correctness vs. simple (enough to show as an example), so feel free to just close this issue if it's meant to be more on the "simple" side of things.

#### Platform information

 - Arch Linux
 - Rust 1.21.0 (stable)

#### Issue

I didn't look too far into the specifics quite yet, so I just left it as "sometimes" in the title. The plugin crash happens when I mash a bunch of keys on my MIDI keyboard, so I assume that means "when I send the plugin a lot of MIDI events at the same time".

I can look into this further in the coming days.

**Comment by robsaunders** [comment]
So the first step to debugging this would be to attach an exception logger to simplelog.

Also, it's not necessarily a midi thing. it's most likely some logic trap occuring in the process loop.

What DAW are you using?

**Comment by crsaracco** [comment]
I'm using Bitwig Studio.

**Comment by jonday-simitive** [comment]
I had this same issue when using the sine example in Bitwig studio. I have a fix on my laptop and have added unit tests to the example which I've been meaning to push up to this repository. I don't have the code on me right now. But as I remember the issue is in midi_pitch_to_freq when pitch is less than 69.

**Comment by plantigrate** [comment]
Yeah so the issue is that the pitch and A4_PITCH are declared unsigned so when a note is below A4 a negative number will cause an 'attempt to substract with overflow' panic. 

So the fix is:
```
    pub fn midi_pitch_to_freq(pitch: u8) -> f64 {
        const A4_PITCH: i8 = 69;
        const A4_FREQ: f64 = 440.0;

        (((pitch as i8 - A4_PITCH) as f64) / 12.).exp2() * A4_FREQ
    }
```

**Comment by crsaracco** [comment]
Can confirm, this fixed it for me as far as I can tell!

**Comment by robsaunders** [comment]
thanks guys!!!! we'll put a fix in (unless someone wants to PR), this code needs a bit of a simplification re-work anyway

**Comment by henrikno** [comment]
Crashed in Live here too (OSX). Stack trace:

```
Thread 3 Crashed:: AudioCalc
0   libsystem_kernel.dylib        	0x00007fff61ad9fce __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff61c17150 pthread_kill + 333
2   libsystem_c.dylib             	0x00007fff61a3630a abort + 127
3   com.rust-vst2.RustVST         	0x000000011ea3379b std::sys_common::util::abort::h4adc0a00ac5d8523 + 91
4   com.rust-vst2.RustVST         	0x000000011ea34e52 rust_panic + 98
5   com.rust-vst2.RustVST         	0x000000011ea34dd6 std::panicking::rust_panic_with_hook::h11521dcff2469787 + 438
6   com.rust-vst2.RustVST         	0x000000011ea34c0f std::panicking::begin_panic::h5f716eb5a72a0014 + 143
7   com.rust-vst2.RustVST         	0x000000011ea34ae3 std::panicking::begin_panic_fmt::hd48510676fb2e905 + 147
8   com.rust-vst2.RustVST         	0x000000011ea34a43 rust_begin_unwind + 35
9   com.rust-vst2.RustVST         	0x000000011ea44554 core::panicking::panic_fmt::h75cea42f9cab1443 + 132
10  com.rust-vst2.RustVST         	0x000000011ea44447 core::panicking::panic::h7c1b2fa4a189009f + 103
11  com.rust-vst2.RustVST         	0x000000011ea1c607 sine_synth::midi_pitch_to_freq::hee9f0934de89a196 + 103
12  com.rust-vst2.RustVST         	0x000000011ea1d0ba _$LT$sine_synth..SineSynth$u20$as$u20$vst2..plugin..Plugin$GT$::process::ha4e86964953b1f82 + 1258
13  com.rust-vst2.RustVST         	0x000000011ea25f12 vst2::interfaces::process_replacing::hbda3469c12198ed9 + 306
14  com.ableton.live              	0x0000000101b9fc80 0x100000000 + 28966016
15  com.ableton.live              	0x0000000101b9fa6e 0x100000000 + 28965486
16  com.ableton.live              	0x0000000101b9226f 0x100000000 + 28910191
17  com.ableton.live              	0x00000001007b7a73 0x100000000 + 8092275
18  com.ableton.live              	0x00000001007d4680 0x100000000 + 8210048
19  com.ableton.live              	0x00000001007baf1c 0x100000000 + 8105756
20  com.ableton.live              	0x00000001007bad7e 0x100000000 + 8105342
21  com.ableton.live              	0x00000001007b02f1 void* std::__1::__thread_proxy<std::__1::tuple<void (TThread::*)(), TThread*> >(void*) + 113
22  libsystem_pthread.dylib       	0x00007fff61c146c1 _pthread_body + 340
23  libsystem_pthread.dylib       	0x00007fff61c1456d _pthread_start + 377
24  libsystem_pthread.dylib       	0x00007fff61c13c5d thread_start + 13
```

**Comment by crsaracco** [comment]
@henrikno take a look at @plantigrate 's fix

**Comment by henrikno** [comment]
Created the fix as a PR: https://github.com/rust-dsp/rust-vst/pull/23
