### ISSUE TITLE
Allow for more thorough testing CI

### ISSUE THREAD

**Issue by piedoom** [rust-dsp/rust-vst#31]
Right now, we test extensively on Windows via Codeship, but not too much on Travis.  We need to add support for 32bit Linux as well as Mac OS.

**Comment by zyvitski** [comment]
Maybe just add `cargo test --release` on to the post build action for travis?

**Comment by piedoom** [comment]
Travis now tests MacOS and automatically publishes tagged commits as releases, yay!  On the todo list: test 64b/32b linux (and mac if that's a thing).  Should be somewhat easy with travis.

**Comment by piedoom** [comment]
I'm going to close this for now since I think CI is pretty robust.  We can update in the future if we need different arch support.
