### ISSUE TITLE
Smoothing Parameter Changes

### ISSUE THREAD

**Issue by atoav** [rust-dsp/rust-vst#37]
I had a great time trying my first things with rust and got a basic-noise generating VST running in ~30 minutes as a person who never compiled any VST before. When I tried to implement changable parameters, things started to crackle etc – just as I expected.

Typically one would implement something like a running average filter of some sorts to avoid sample discontinuities (various strategies are [discussed in this thread on kvraudio.com](kvraudio.com) – a good read).  

Now my thought: wouldn't it be greate if this would be part of the API?
- Smooth Parameter Changes (moving average filter with various lengths)
- Different Update Rates (sample accurate or every nth sample)  

I am a beginner in rust, so I know my skills are not good enough to implement a nice solution for this, but it would definitly rock!

**Comment by robsaunders** [comment]
Hey there! Great idea - in the interests of keeping the crate a lean interface to VST, this kind of functionality should probably be put into a separate crate on rust-dsp, or implemented as an example rather than being something within the core library.

The case for a crate would be, if we were to release an audiounit interface (something we would love to do, but I currently lack the time resources - one day), it could be useful across those interfaces as a higher level abstraction.

**Comment by Boscop** [comment]
@atoav I use this in my VSTs:
```rust
use num_traits::Float;
use asprim::AsPrim;

use util::mix;

#[derive(Default)]
pub struct Smoother<F> {
	cur: F,
	last: F,
	time_s: F,
	fs: F,
	smooth: F,
}

impl<F: Float + AsPrim> Smoother<F> {
	pub fn set_val(&mut self, x: F) { self.cur = x; }

	pub fn val(&self) -> F { self.last }

	pub fn changed(&self) -> bool { self.cur != self.last }

	pub fn set_time_ms(&mut self, ms: F) {
		self.time_s = ms * 0.001.as_();
		self.bake();
	}

	pub fn set_sample_rate(&mut self, fs: F) {
		self.fs = fs;
		self.bake();
	}

	fn bake(&mut self) {
		let samples = (self.time_s * self.fs).max(F::one());
		self.smooth = 0.69314718056.as_::<F>() / samples;
	}

	pub fn smoothed(&mut self) -> F {
		let r = mix(self.last, self.cur, self.smooth);
		self.last = r;
		r
	}
}
```
adapted from [here](https://github.com/JordanTHarris/VAStateVariableFilter/blob/master/Source/Utilities/ParameterSmoother.h#L123).

**Comment by Boscop** [comment]
@atoav: Does this work for you? It's working fine in my filter to smooth out the cutoff (and other) param changes.. 
I'm also using this for portamento to smooth pitch, and I'm using it for beat-sync (smooth alignment of beat grids over time for automatic beat-matching).

Btw, this is my current version, I added a constructor for convenience and `set_origin` method (useful for the smooth quantization) and convenient bool smoothing functions:
```rust
use num_traits::Float;
use asprim::AsPrim;

use util::mix;

#[derive(Default, Copy, Clone, Serialize, Deserialize)]
pub struct Smoother<F> {
	target: F,
	cur: F,
	time_s: F,
	fs: F,
	smooth: F,
}

impl<F: Float + AsPrim> Smoother<F> {
	pub fn new(fs: F, ms: F, x: F) -> Self {
		let mut r = Self {
			target: x,
			cur: x,
			time_s: ms * 0.001.as_(),
			fs,
			smooth: F::one(),
		};
		r.bake();
		r
	}

	pub fn set_target(&mut self, x: F) { self.target = x; }

	pub fn set_origin(&mut self, x: F) { self.cur = x; }

	pub fn val(&self) -> F { self.cur }

	pub fn changed(&self) -> bool { self.target != self.cur }

	pub fn set_time_ms(&mut self, ms: F) {
		self.time_s = ms * 0.001.as_();
		self.bake();
	}

	pub fn set_sample_rate(&mut self, fs: F) {
		self.fs = fs;
		self.bake();
	}

	fn bake(&mut self) {
		let samples = (self.time_s * self.fs).max(F::one());
		self.smooth = 0.69314718056.as_::<F>() / samples;
	}

	pub fn process(&mut self) -> F {
		let r = mix(self.cur, self.target, self.smooth);
		self.cur = r;
		r
	}

	pub fn set_target_b(&mut self, x: bool) { self.target = (x as u8).as_(); }

	pub fn process_b(&mut self) -> bool { self.process() >= 0.5.as_() }
}
```

**Comment by antonok-edm** [comment]
@Boscop would you mind also sharing your implementation of util::mix?

**Comment by zyvitski** [comment]
Closing because is out of the scope of this crate. We can investigate the need for such a utility as a separate crate. Will discuss on telegram.

**Comment by Boscop** [comment]
@antonok-edm Like GLSL's `mix` function to interpolate between `a` and `b`:

```rust
#[inline(always)]
pub fn mix<F: Float>(a: F, b: F, x: F) -> F {
	(F::one() - x) * a + x * b
}
```
