### ISSUE TITLE
publish to crates as `vst`

### ISSUE THREAD

**Issue by conundrumer** [rust-dsp/rust-vst#4]
also update readme (the cargo.toml and urls and example `s/vst2/vst/`) when that happens

**Comment by piedoom** [comment]
How should we publish?  We can either:

- Manually push stuff to crates.io when a new release is set

- Set up CI to push a new version on a tagged build success on master

**Comment by conundrumer** [comment]
How about we start with manually pushing, since we've been manually testing and we don't have any automated testing for the CI to run?

**Comment by piedoom** [comment]
Sounds like a good plan.

**Comment by zyvitski** [comment]
I vote for 'vst'

**Comment by piedoom** [comment]
Same here.  So we don't spam too much, react with a 👍 to vote for `vst`, and any other emoji for something else (please comment your suggestion).  Upvote other suggestions to cast a vote.

**Comment by piedoom** [comment]
We're published on [crates.io!](https://crates.io/crates/vst)
