### ISSUE TITLE
Info name and vendor should be &'static str because they should be constants anyway

### ISSUE THREAD

**Issue by Boscop** [rust-dsp/rust-vst#42]
It would be enough if `Info`'s `name` and `vendor` were `&'static str` instead of `String`, because they should never change between calls anyway, and it would not require writing `.to_string()` for both when instantiating the `Info` struct, it is required now:
```rust
		Info {
			name: "name".to_string(),
			vendor: "vendor".to_string(),
```
Same with `Host::get_info() -> (isize, String, String)` which should also return `&'static str` for vendor and product names (they should also be constants that don't change between calls). 
(But I guess it's not guaranteed that all (C++) hosts return actual pointers to static strings from this opcall..)

**Comment by askeksa** [comment]
That the strings are constant throughout the lifetime of a plugin instantiation does not mean that they are necessarily static strings embedded into the plugin binary. That is an implementation detail of the plugin. I can easily imagine a plugin wanting to generate these strings from some internal metadata, or perhaps even from data files in the plugin distribution. Forcing the strings to be `'static` makes such an implementation impossible.

**Comment by piedoom** [comment]
Should those values be allowed to change?  Is there any limitations in the VST spec?

**Comment by Boscop** [comment]
I'm not aware of the VST spec specifying that the values shouldn't change but as with many things, most hosts in the wild are making assumptions.. I would try to avoid changing the plugin name/vendor, hosts may associate user presets with it (not sure how common plugin ID collisions are. Hosts may be using a combination of plugin ID, name and vendor to associate its data).
But having a non-changing name/vendor loaded from metadata would work.
