### ISSUE TITLE
Docs do not automatically update

### ISSUE THREAD

**Issue by piedoom** [rust-dsp/rust-vst#7]
Master PRs that are accepted do not trigger a rebuild of the docs

**Comment by conundrumer** [comment]
I remember this was mentioned somewhere: https://docs.rs/

**Comment by piedoom** [comment]
There's a way to push it to our GH pages so we don't need to publish stuff on cargo, and an easy script to get it working.  In the travis yml I just needed to add this (we'd need to make sure it only does this on master branch pushes)

```
after_success: |
    cargo rustdoc \
    && echo '<meta http-equiv=refresh content=0;url=rust-vst/index.html>' > target/doc/index.html && \
    sudo pip install ghp-import && \
    ghp-import -n target/doc && \
    git push -qf https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
``` 

Of course that's only considering it builds correctly on Unix systems, I'm not sure if there's a way to do the same on appveyor.
