### ISSUE TITLE
Telegram spam blocker timer got me

### ISSUE THREAD

**Issue by Engid** [rust-dsp/rust-vst#79]
Hey, I tried to join the telegram chat and I didn't notice the tiny box at the bottom that said I would be locked out if I didn't click on it. I had scrolled up while reading the chat and missed the warning. Could someone please unblock me or something? I promise I won't spam 😄

**Comment by zyvitski** [comment]
Give me a moment and I will take care of it for you.

**Comment by zyvitski** [comment]
Please try again now. And remember to press the button.

**Comment by zyvitski** [comment]
Resolved
